image: WMF 5

environment:
  GithubApiKey:
    secure: RNKZCETbNKm4H3Mi/ykEroQvSyVCOc3eg8/XKuLiAG7CPhNpKyLuisfj68aexqD1

# only build pushes to master - can work on other branches without triggering builds
branches:
  only:
    - master

skip_tags: true

install:
    - ps: |
        Install-PackageProvider -Name NuGet -MinimumVersion '2.8.5.201' -Force -Verbose
        Install-Module InvokeBuild -Force

build: false

test_script:
    - ps: Invoke-Build -Task Test

after_test:
    - ps: |
        if([string]::IsNullOrEmpty($env:APPVEYOR_PULL_REQUEST_NUMBER)) { Invoke-Build -Task DeployGithub }
